version: "3"

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ../../:/var/www/web
    links:
      - mysql
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=satan
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - 3306:3360

  adminer:
    image: adminer
    links:
      - mysql
    ports:
      - 8082:8080
